<?php
    #EL INDEX: SALIDA DE LAS VISTAS AL USUARIO Y TAMBIEN A TRAVES  DE EL ENVIAREMOS LAS DISTINTAS ACCIONES QUE EL USUARIO ENVÍE AL CONTROLADOR
    
    #REQUIRE() ESTABLECE QUE EL CÓDIGO  DEL ARCHIVO INVOCADO ES REQUERIDO, ES DECIR, OBLIGATORIO PARA EL FUNCIONAMIENTO DEL PROGRAMA. POR ELLO,
    #SI EL ARCHIVO ESPECIFICADO EN LA FUNCION REQUIRE() NO SE ENCUENTRA SALTARÁ UN ERROR "PHP FATAL ERROR" Y EL PROGRAMA PHP SE DETENDRÁ

    #LA VERSIÓN REQUIRE_ONCE() FUNCIONAN DE LA MISMA FORMA QUE SUS RESPECTIVO, SALVO QUE, AL UTILIZAR LA VERSIÓN _ONCE, SE IMPIDE LA CARGA DE UN MISMO
    #ARCHIVO MÁS DE UNA VEZ.

    #SI REQUERIMOS EL MISMO CODIGO MÁS DE UNA VEZ CORREMOS EL RIESGO DE  REDECLARACIONES DE VARIABLES, FUNCIONES O CLASES 
    require_once "controllers/controller.php";
    require_once "models/model.php";
    $mvc = new MvcController();

    $mvc -> plantilla();
?>